services:
  db:
    image: postgres:17
    environment:
      - POSTGRESS_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=betternewdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - betternews-network
    ports:
      - "5432:5432"

networks:
  betternews-network:
    driver: bridge

volumes:
  postgres-data: